version: "3.8"
services:
  k8s-mcp-server:
    image: ghcr.io/alexei-led/k8s-mcp-server:latest
    volumes:
      - ~/.kube:/home/appuser/.kube:ro
    ports:
      - "8081:8080"
  # Add other MCP servers as needed
